### PR TITLE
Add icon and fanart

### PR DESCRIPTION
**Pull request by MetalChris**
'Unofficial' fanart and icon. Feel free to use them if you like. I can do something different if you have other images you'd like to use instead, or if you want the text rearranged.

### CODE REVIEW

**Comment by MetalChris** [comment]
'Unofficial' fanart and icon.  Feel free to use them if you like.  I can do something different if you have other images you'd like to use instead, or if you want the text rearranged.

**Comment by emilsvennesson** [comment]
Thanks for the PR!

I do like the icon, but personally I'd prefer something a bit more simplistic. The official logo uses a plain dark blue background, and maybe we should resemble that a bit, though without using the official font/Fox logo. I am a total disaster when it comes to anything related to art, so if you've got another idea, please don't hesitate to tell me!

Also, Kodi now allows a 512x512 resolution for the icon in the official repository so it'd be great to use that rather than 256x256. :-)

Thanks again for helping out!

**Comment by MetalChris** [comment]
I made a "plain" icon, 512x512.  Take a look [here](http://imgur.com/a/8flhv) at the 3rd and 4th images, and you can compare an official icon with my unofficial one.  Let me know what you think.  Of course, feel free to use it if you like.

**Comment by emilsvennesson** [comment]
Thanks, we're definitely getting closer. :-) Maybe we should use a different font to distinguish us a bit more from the original logo? The current one also seem to have some weird blurriness (take a close look at the borders of the O in 'FOX').

**Comment by MetalChris** [comment]
Yep, the text got a little fuzzy when I scaled it down to 512x512.  Take a look at image 5 on the [same page](http://imgur.com/a/8flhv).  Different font, all caps.  I can adjust the size of each word to make the text fit together more like the 'official' icon.  Let me know if I'm headed in the right direction.

**Comment by emilsvennesson** [comment]
@MetalChris The latest icon looks neat. :-) It would be cool to see how it looks with the text fit together, but keep it mind that we don't want to be /too/ similar to the official logo. I just want to make sure that this project won't be a subject to any copyright trolls. :smirk:

**Comment by emilsvennesson** [comment]
I found a cool, free image I thought we could use as fanart: 70111386a6ea7e981ae269679d1e4a2f024f5bf4.

**Comment by MetalChris** [comment]
I used a free stadium pic in the fanart I had made since Fox Sports shows more than one sport, many of which are played in stadiums.  But it's your add-on, whatever you want for fanart and icons is up to you.  I like the football, and football is my second favorite sport, so that pic is cool and would be fine with me.  I uploaded another [icon candidate](http://imgur.com/7fC51lg), this one with the text arranged more like the [official icon](http://imgur.com/bSBSes0).

**Comment by emilsvennesson** [comment]
The latest icon looks great! I feel like it's time for a merge. :-). Would you mind adding it to the PR and perhaps rebase and squash your commits? Big thanks for helping out!

I'll stick with the fanart I've added for now, but I might update it later if I find another cool more generic sports image.

**Comment by MetalChris** [comment]
Rebase and squash?  I've never done that before, but I'll look into it this morning and learn!

**Comment by emilsvennesson** [comment]
If you're running into trouble, you can also just add the icon as a new commit and I'll manually cherry-pick it. 

Git can be a PITA sometimes. 😃

**Comment by emilsvennesson** [comment]
@MetalChris Could you make a commit with just the icon? I've actually already included the fanart. :-)

**Comment by emilsvennesson** [comment]
@MetalChris Never mind, it worked out anyways.

Thanks a lot for helping me out with this! :grin:

**Comment by MetalChris** [comment]
Happy to help out, making an icon is pretty minor compared to coding the actual add-on.  You've done a heck of a job!  And yes, git can be a major PITA!  Powerful as all hell, but sometimes completely counter intuitive!

**Comment by emilsvennesson** [comment]
@MetalChris Amen to that, haha!

**Pull request closed without merging**
